# -*- coding: utf-8 -*-
"""Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qefXhBTnSuDgCuwjyJm6uLQWpKgXtXy

Q1. Given two strings s and t, return true if t is an anagram of s, and false otherwise
"""

def is_it_anagram(a, b):
    return sorted(a) == sorted(b)

a1 = "sharp"
b1 = "harps"
print(is_it_anagram(a1, b1))