# -*- coding: utf-8 -*-
"""Q10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-817KKsWYI-BHnRzBgKoNHHsPlkrKM14

Problem 10: We need to transpose a 2D integer array matrix.
"""

def transpose_matrix(matrix):
    transposed = []
    for i in range(len(matrix[0])):
        new_row = []
        for row in matrix:
            new_row.append(row[i])
        transposed.append(new_row)
    return transposed


matrix_input = [
    [2, 9, 0],
    [7, 2, 0],
    [0, 4, 1]
]
print(transpose_matrix(matrix_input))

