# -*- coding: utf-8 -*-
"""Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMuQ-7hTg1qkhu7dyIt0nX97cKzz14wx

Problem 2: We need to count the frequency of each character in a string, considering upper and lower case letters separately, and ignoring spaces.
"""

def frequency_of_characters(s):
    freq = {}
    for char in s:
        if char.isalpha():
            if char in freq:
                freq[char] += 1
            else:
                freq[char] = 1

    sorted_chars = sorted(freq.keys())
    for char in sorted_chars:
        print("The character ", char ,", appears :", freq[char] ," number of times.")

input_str = "The quick brown fox jumped over the lazy dog"
frequency_of_characters(input_str)