# -*- coding: utf-8 -*-
"""Q5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CxRsflmUb0WMdPrh0IS21aJDs244tH0t

Problem 5: Alternative way, that is taking images from a URL
"""

# We need some additional packages
!pip install opencv-python-headless numpy requests pillow

import cv2
import numpy as np
import requests
from PIL import Image
from io import BytesIO
from google.colab.patches import cv2_imshow

def detect_edges_from_url(image_url):
    response = requests.get(image_url)
    img = Image.open(BytesIO(response.content)).convert('RGB')
    img = np.array(img)

    # Converting to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    edges = cv2.Canny(gray, 100, 200)

    cv2_imshow(cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
    cv2_imshow(edges)

# Example:
image_url = "https://www.omlet.nl/images/cache/438/512/90/Dog-Labrador_Retriever-A_healthy_adult_Labrador_sitting%2C_waiting_for_some_attention_from_it%27s_owner.webp"
detect_edges_from_url(image_url)