# -*- coding: utf-8 -*-
"""Q7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FarMJ1RQ9zDo1A69GDdsPK4AgsqBNCF8

Problem 7: For each product, we need to find the minimum prime factor of its MRP.
"""

def smallest_prime_factor(n):
    if n <= 1:
        return n
    for i in range(2, n + 1):
        if n % i == 0:
            return i
    return n

def amount_roy_pays(N, prices):
    results = []
    for price in prices:
        min_prime = smallest_prime_factor(price)
        roy_pays = price - min_prime
        results.append(roy_pays)
    return results


N = 2    # Array Size
prices = [5, 10]      # Value of prices!
print(amount_roy_pays(N, prices))